### ISSUE TITLE
220624

### ISSUE THREAD

**Issue by huisu-noh** [huisu-noh/react-practice#2]
## Description

 section 8  연습프로젝트 하기

## Todo List

- [x] 사용자 컴포넌트 추가
- [x] 재사용 가능한 카드 컴포넌트 추가
- [x] 재사용 가능한 버튼 컴포넌트 추가
- [ ] 사용자 입력 State 관리
- [ ] 검증 추가 및 로직 재설정
- [ ] 사용자 목록 컴포넌트 추가
- [ ]  State를 통해 사용자 목록 관리
- [ ] ErrorModal 컴포넌트 추가
- [ ] 오류 State 관리
